services:
  - type: static
    name: redgaon-gp
    rootDir: client
    buildCommand: npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html